### ISSUE TITLE
Doesn't work on Chrome?

### ISSUE THREAD

**Issue by bpisano** [mvllow/tailwindcss-safe-area#1]
Hi,

Thanks for this nice little package. This is exactly what I was looking for. It works pretty well on Safari and Firefox, but I couldn't get it to work on Chrome. I'm using React, and here is the code of a `div` at the root of the app:

```html
<div className="bg-red-500 h-screen-safe">Test</div>
```

And the result on different browsers.

### Safari iOS

<img width="565" alt="Capture d’écran 2022-10-18 à 20 53 24" src="https://user-images.githubusercontent.com/16155946/196519041-dad4db5c-0fc1-45d2-a8e1-93ea1524547a.png">

### Safari macOS

<img width="934" alt="Capture d’écran 2022-10-18 à 20 53 41" src="https://user-images.githubusercontent.com/16155946/196519184-c93d7d14-693c-44de-a3a9-68f0512a6ada.png">

### Firefox

<img width="875" alt="Capture d’écran 2022-10-18 à 20 53 29" src="https://user-images.githubusercontent.com/16155946/196519243-fd8075f7-645d-4191-9889-b486b04c586d.png">

### Chrome

<img width="910" alt="Capture d’écran 2022-10-18 à 20 55 07" src="https://user-images.githubusercontent.com/16155946/196519308-5bacc39e-4239-4231-9766-0b090cbbd954.png">

On Chrome, the `div` doesn't want to fit the window height. Do you have any idea of the cause of the issue? Maybe I'm missing something.

**Comment by mvllow** [comment]
Thanks for the report! The relevant lines should be https://github.com/mvllow/tailwindcss-safe-area/blob/70dbef61557b07e26b07a6167e13a377ba3c4625/index.js#L64-L69

I'm guessing `calc(100vh - (env(safe-area-inset-top) + env(safe-area-inset-bottom)))` is the culprit. Will have to play around with it; happy to accept a PR if someone beats me to it :)

**Comment by bpisano** [comment]
After days of investigation, I finally found that on Chrome, you need to specify `height: -webkit-fill-available;` on the `html`, `body` and `root` tags. The `root` tag is specific to react and is used to insert your components to the DOM.

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  html {
    height: -webkit-fill-available;
  }

  body {
    height: -webkit-fill-available;
  }

  #root {
    height: -webkit-fill-available;
  }
}
```

Then, on your components, you can safely use your package on any browser.

```tsx
import { FunctionComponent } from 'react';

export const App: FunctionComponent = () => {
  return (
    <div className="min-h-screen-safe bg-red-500" />
  );
};
```

I don't think you can handle this behavior directly in your package. But updating the documentation could be nice. I can open a PR to do it. What do you think?

**Comment by mvllow** [comment]
Appreciate the investigation! A PR to update the documentation would be lovely. Not sure if tailwind has a way for plugins to set any of that automatically but could explore that in the future :)
