### ISSUE TITLE
Should height-safe-offset-8 work?

### ISSUE THREAD

**Issue by maxfriedmann** [mvllow/tailwindcss-safe-area#10]
I guess I misunderstood the docs since I thought `*-safe-offset-{value}` would mean I could do something like `height-safe-offset-8`?

**Comment by mvllow** [comment]
It should be `h-safe-offset-8`, marching tailwind's height classes :)

**Comment by maxfriedmann** [comment]
hach, embarrassing! Thanks a lot, that works.
